const FLASHCARDS = {
  HS: [
    // ── BIOLOGY (60) ──────────────────────────────────────────────────────────
    { term: "Cell Membrane", def: "Phospholipid bilayer controlling what enters and exits cells.", subject: "Biology" },
    { term: "Mitochondria", def: "Organelle producing ATP via cellular respiration.", subject: "Biology" },
    { term: "Nucleus", def: "Contains DNA and directs all cell activities.", subject: "Biology" },
    { term: "Ribosome", def: "Synthesizes proteins from mRNA instructions.", subject: "Biology" },
    { term: "Chloroplast", def: "Site of photosynthesis in plant cells.", subject: "Biology" },
    { term: "Cell Wall", def: "Rigid structure providing support in plants and bacteria.", subject: "Biology" },
    { term: "Endoplasmic Reticulum", def: "Network for protein and lipid synthesis.", subject: "Biology" },
    { term: "Golgi Apparatus", def: "Packages and ships proteins out of the cell.", subject: "Biology" },
    { term: "Lysosome", def: "Contains digestive enzymes to break down waste.", subject: "Biology" },
    { term: "Vacuole", def: "Storage organelle; large central vacuole in plant cells.", subject: "Biology" },
    { term: "Mitosis", def: "Cell division producing two identical diploid daughter cells.", subject: "Biology" },
    { term: "Meiosis", def: "Division producing four haploid gametes with crossing over.", subject: "Biology" },
    { term: "DNA Replication", def: "Copying DNA before cell division; semiconservative.", subject: "Biology" },
    { term: "Transcription", def: "Making mRNA from DNA template in the nucleus.", subject: "Biology" },
    { term: "Translation", def: "Building proteins from mRNA at ribosomes.", subject: "Biology" },
    { term: "Mutation", def: "Change in DNA sequence; source of genetic variation.", subject: "Biology" },
    { term: "Dominant Allele", def: "Expressed when only one copy is present.", subject: "Biology" },
    { term: "Recessive Allele", def: "Only expressed when two copies are present.", subject: "Biology" },
    { term: "Homozygous", def: "Two identical alleles for a gene.", subject: "Biology" },
    { term: "Heterozygous", def: "Two different alleles for a gene.", subject: "Biology" },
    { term: "Phenotype", def: "Observable physical traits of an organism.", subject: "Biology" },
    { term: "Genotype", def: "Genetic makeup of an organism.", subject: "Biology" },
    { term: "Crossing Over", def: "Exchange of DNA between homologous chromosomes in meiosis I.", subject: "Biology" },
    { term: "Natural Selection", def: "Better-adapted individuals survive and reproduce more.", subject: "Biology" },
    { term: "Evolution", def: "Change in allele frequencies in a population over generations.", subject: "Biology" },
    { term: "Speciation", def: "Formation of new species from one ancestral population.", subject: "Biology" },
    { term: "Photosynthesis", def: "Converting light energy to glucose using CO₂ and H₂O.", subject: "Biology" },
    { term: "Cellular Respiration", def: "Breaking down glucose to produce ATP.", subject: "Biology" },
    { term: "Glycolysis", def: "First stage of respiration; glucose → pyruvate in cytoplasm.", subject: "Biology" },
    { term: "Krebs Cycle", def: "Citric acid cycle in mitochondrial matrix; 2 ATP per glucose.", subject: "Biology" },
    { term: "Electron Transport Chain", def: "Final ATP production on inner mitochondrial membrane.", subject: "Biology" },
    { term: "Fermentation", def: "Anaerobic ATP production; produces lactic acid or ethanol.", subject: "Biology" },
    { term: "Enzyme", def: "Biological catalyst lowering activation energy.", subject: "Biology" },
    { term: "Active Site", def: "Region on enzyme where substrate binds.", subject: "Biology" },
    { term: "Competitive Inhibition", def: "Inhibitor blocks active site, competing with substrate.", subject: "Biology" },
    { term: "Osmosis", def: "Water movement across semipermeable membrane toward higher solute.", subject: "Biology" },
    { term: "Active Transport", def: "Moving molecules against concentration gradient using ATP.", subject: "Biology" },
    { term: "Endocytosis", def: "Cell engulfing substances by membrane folding inward.", subject: "Biology" },
    { term: "Exocytosis", def: "Releasing substances outside cell via vesicle fusion.", subject: "Biology" },
    { term: "Neuron", def: "Nerve cell transmitting electrical signals via action potentials.", subject: "Biology" },
    { term: "Action Potential", def: "Electrical impulse traveling along a neuron; all-or-nothing.", subject: "Biology" },
    { term: "Synapse", def: "Gap between neurons where signals transfer via neurotransmitters.", subject: "Biology" },
    { term: "Hormone", def: "Chemical messenger secreted by endocrine glands into bloodstream.", subject: "Biology" },
    { term: "Insulin", def: "Pancreatic hormone lowering blood glucose.", subject: "Biology" },
    { term: "Homeostasis", def: "Maintaining stable internal body conditions.", subject: "Biology" },
    { term: "Antibody", def: "Protein produced by B cells targeting specific antigens.", subject: "Biology" },
    { term: "Antigen", def: "Foreign molecule triggering immune response.", subject: "Biology" },
    { term: "Vaccine", def: "Prepares immune memory without causing full disease.", subject: "Biology" },
    { term: "Food Web", def: "Network of feeding relationships in an ecosystem.", subject: "Biology" },
    { term: "Trophic Level", def: "Position in food chain based on energy source.", subject: "Biology" },
    { term: "Nitrogen Cycle", def: "Movement of nitrogen through ecosystem; fixed by bacteria.", subject: "Biology" },
    { term: "Carbon Cycle", def: "Movement of carbon through biosphere, atmosphere, and oceans.", subject: "Biology" },
    { term: "Biome", def: "Large ecological zone with distinct climate and organisms.", subject: "Biology" },
    { term: "Hardy-Weinberg Equilibrium", def: "Allele frequencies stable without evolutionary forces.", subject: "Biology" },
    { term: "Plasmid", def: "Small circular DNA in bacteria used in genetic engineering.", subject: "Biology" },
    { term: "CRISPR", def: "Gene-editing tool using guided RNA to cut DNA precisely.", subject: "Biology" },
    { term: "Mitotic Spindle", def: "Microtubule structure separating chromosomes during mitosis.", subject: "Biology" },
    { term: "Stem Cell", def: "Undifferentiated cell capable of becoming specialized cell types.", subject: "Biology" },
    { term: "Apoptosis", def: "Programmed cell death; removes damaged or unneeded cells.", subject: "Biology" },
    { term: "Coevolution", def: "Two species evolving in response to each other.", subject: "Biology" },

    // ── CHEMISTRY (55) ────────────────────────────────────────────────────────
    { term: "Atomic Number", def: "Number of protons in an atom; defines the element.", subject: "Chemistry" },
    { term: "Mass Number", def: "Total protons plus neutrons in nucleus.", subject: "Chemistry" },
    { term: "Isotope", def: "Atoms of same element with different neutron count.", subject: "Chemistry" },
    { term: "Electronegativity", def: "Atom's ability to attract electrons in a bond.", subject: "Chemistry" },
    { term: "Ionic Bond", def: "Electrons transferred from metal to nonmetal.", subject: "Chemistry" },
    { term: "Covalent Bond", def: "Electrons shared between two nonmetal atoms.", subject: "Chemistry" },
    { term: "Polar Covalent Bond", def: "Unequal electron sharing due to electronegativity difference.", subject: "Chemistry" },
    { term: "Hydrogen Bond", def: "Weak attraction between H and a F, O, or N atom.", subject: "Chemistry" },
    { term: "Valence Electrons", def: "Outer shell electrons involved in bonding.", subject: "Chemistry" },
    { term: "VSEPR Theory", def: "Electron pairs repel to determine molecular geometry.", subject: "Chemistry" },
    { term: "Molarity", def: "Moles of solute per liter of solution; mol/L.", subject: "Chemistry" },
    { term: "Mole", def: "6.022 × 10²³ particles of a substance.", subject: "Chemistry" },
    { term: "Stoichiometry", def: "Quantitative relationships between reactants and products.", subject: "Chemistry" },
    { term: "Limiting Reagent", def: "Reactant consumed first, stopping the reaction.", subject: "Chemistry" },
    { term: "Endothermic Reaction", def: "Reaction absorbing heat from surroundings; ΔH > 0.", subject: "Chemistry" },
    { term: "Exothermic Reaction", def: "Reaction releasing heat to surroundings; ΔH < 0.", subject: "Chemistry" },
    { term: "Enthalpy", def: "Heat content of system at constant pressure.", subject: "Chemistry" },
    { term: "Entropy", def: "Measure of disorder or randomness in a system.", subject: "Chemistry" },
    { term: "Gibbs Free Energy", def: "ΔG = ΔH − TΔS; negative ΔG means spontaneous reaction.", subject: "Chemistry" },
    { term: "Activation Energy", def: "Minimum energy needed to start a chemical reaction.", subject: "Chemistry" },
    { term: "Equilibrium", def: "Forward and reverse reaction rates are equal.", subject: "Chemistry" },
    { term: "Le Chatelier's Principle", def: "System shifts to oppose changes in equilibrium conditions.", subject: "Chemistry" },
    { term: "Acid", def: "Proton donor; pH below 7.", subject: "Chemistry" },
    { term: "Base", def: "Proton acceptor; pH above 7.", subject: "Chemistry" },
    { term: "pH", def: "Negative log of hydrogen ion concentration.", subject: "Chemistry" },
    { term: "Buffer", def: "Solution resisting pH changes when acid or base added.", subject: "Chemistry" },
    { term: "Oxidation", def: "Loss of electrons; increase in oxidation state.", subject: "Chemistry" },
    { term: "Reduction", def: "Gain of electrons; decrease in oxidation state.", subject: "Chemistry" },
    { term: "Galvanic Cell", def: "Spontaneous redox reaction generates electrical energy.", subject: "Chemistry" },
    { term: "Electrolysis", def: "Electric current drives non-spontaneous chemical reaction.", subject: "Chemistry" },
    { term: "Ideal Gas Law", def: "PV = nRT; relates pressure, volume, temperature, moles.", subject: "Chemistry" },
    { term: "Boyle's Law", def: "Pressure and volume inversely proportional at constant T.", subject: "Chemistry" },
    { term: "Charles's Law", def: "Volume and temperature directly proportional at constant P.", subject: "Chemistry" },
    { term: "Dalton's Law", def: "Total pressure equals sum of all partial pressures.", subject: "Chemistry" },
    { term: "Intermolecular Forces", def: "Attractions between molecules; affect boiling/melting points.", subject: "Chemistry" },
    { term: "Colligative Properties", def: "Depend on number of solute particles, not their identity.", subject: "Chemistry" },
    { term: "Nuclear Fission", def: "Heavy nucleus splits into smaller nuclei releasing energy.", subject: "Chemistry" },
    { term: "Nuclear Fusion", def: "Light nuclei combine to form heavier nucleus, releasing energy.", subject: "Chemistry" },
    { term: "Half-Life", def: "Time for half of radioactive sample to decay.", subject: "Chemistry" },
    { term: "Hess's Law", def: "Enthalpy change independent of reaction pathway.", subject: "Chemistry" },
    { term: "Reaction Rate", def: "Speed at which reactants convert to products.", subject: "Chemistry" },
    { term: "Catalyst", def: "Lowers activation energy without being consumed.", subject: "Chemistry" },
    { term: "Electron Configuration", def: "Arrangement of electrons in an atom's orbitals.", subject: "Chemistry" },
    { term: "Alkali Metals", def: "Group 1; very reactive, lose one electron easily.", subject: "Chemistry" },
    { term: "Halogens", def: "Group 17; highly reactive nonmetals gaining one electron.", subject: "Chemistry" },
    { term: "Noble Gases", def: "Group 18; stable, full outer electron shells.", subject: "Chemistry" },
    { term: "Empirical Formula", def: "Simplest whole-number ratio of atoms in compound.", subject: "Chemistry" },
    { term: "Molecular Formula", def: "Actual number of each atom in one molecule.", subject: "Chemistry" },
    { term: "Solubility", def: "Maximum solute dissolving in solvent at given temperature.", subject: "Chemistry" },
    { term: "Titration", def: "Adding known solution to unknown to find concentration.", subject: "Chemistry" },
    { term: "Redox Reaction", def: "Simultaneous oxidation and reduction between reactants.", subject: "Chemistry" },
    { term: "London Dispersion Forces", def: "Weakest intermolecular force; between all molecules.", subject: "Chemistry" },
    { term: "Dipole-Dipole", def: "Attraction between polar molecules' positive and negative ends.", subject: "Chemistry" },
    { term: "Lattice Energy", def: "Energy released forming ionic solid from gaseous ions.", subject: "Chemistry" },
    { term: "Spectroscopy", def: "Analyzing light absorbed/emitted to identify substances.", subject: "Chemistry" },

    // ── PHYSICS (55) ──────────────────────────────────────────────────────────
    { term: "Newton's First Law", def: "Object stays at rest or motion unless a net force acts.", subject: "Physics" },
    { term: "Newton's Second Law", def: "F = ma; net force equals mass times acceleration.", subject: "Physics" },
    { term: "Newton's Third Law", def: "Every action has equal and opposite reaction force.", subject: "Physics" },
    { term: "Momentum", def: "Mass times velocity; conserved in closed system.", subject: "Physics" },
    { term: "Impulse", def: "Change in momentum; equals force times time.", subject: "Physics" },
    { term: "Work", def: "Force times displacement in direction of force; joules.", subject: "Physics" },
    { term: "Power", def: "Rate of doing work; W = work/time; measured in watts.", subject: "Physics" },
    { term: "Kinetic Energy", def: "Energy of motion; KE = ½mv².", subject: "Physics" },
    { term: "Potential Energy", def: "Stored energy based on position or condition.", subject: "Physics" },
    { term: "Gravitational PE", def: "PE = mgh; depends on mass, gravity, and height.", subject: "Physics" },
    { term: "Conservation of Energy", def: "Total energy in isolated system remains constant.", subject: "Physics" },
    { term: "Simple Harmonic Motion", def: "Periodic oscillation with restoring force proportional to displacement.", subject: "Physics" },
    { term: "Frequency", def: "Number of cycles per second; measured in hertz.", subject: "Physics" },
    { term: "Period", def: "Time for one complete oscillation cycle.", subject: "Physics" },
    { term: "Transverse Wave", def: "Oscillation perpendicular to wave direction; light, water.", subject: "Physics" },
    { term: "Longitudinal Wave", def: "Oscillation parallel to wave direction; sound waves.", subject: "Physics" },
    { term: "Amplitude", def: "Maximum displacement from equilibrium; related to energy.", subject: "Physics" },
    { term: "Wavelength", def: "Distance between consecutive crests or compressions.", subject: "Physics" },
    { term: "Speed of Light", def: "3 × 10⁸ m/s in vacuum; maximum speed in universe.", subject: "Physics" },
    { term: "Reflection", def: "Wave bouncing off a surface; angle in equals angle out.", subject: "Physics" },
    { term: "Refraction", def: "Wave bending when changing medium due to speed change.", subject: "Physics" },
    { term: "Diffraction", def: "Wave spreading around obstacles or through openings.", subject: "Physics" },
    { term: "Interference", def: "Waves combining; constructive adds, destructive cancels.", subject: "Physics" },
    { term: "Doppler Effect", def: "Frequency shifts higher approaching, lower receding.", subject: "Physics" },
    { term: "Coulomb's Law", def: "Electrostatic force proportional to charges, inversely to distance².", subject: "Physics" },
    { term: "Electric Field", def: "Region where a charge experiences force; E = F/q.", subject: "Physics" },
    { term: "Electric Potential", def: "Potential energy per unit charge; measured in volts.", subject: "Physics" },
    { term: "Ohm's Law", def: "V = IR; voltage equals current times resistance.", subject: "Physics" },
    { term: "Series Circuit", def: "Components in single path; same current throughout.", subject: "Physics" },
    { term: "Parallel Circuit", def: "Components in multiple paths; same voltage across each.", subject: "Physics" },
    { term: "Capacitor", def: "Stores electric charge between two conductors.", subject: "Physics" },
    { term: "Faraday's Law", def: "Changing magnetic flux through loop induces EMF.", subject: "Physics" },
    { term: "Lenz's Law", def: "Induced current direction opposes change in magnetic flux.", subject: "Physics" },
    { term: "Transformer", def: "Changes AC voltage using electromagnetic induction.", subject: "Physics" },
    { term: "Photoelectric Effect", def: "Light ejects electrons from metal; photon energy = hf.", subject: "Physics" },
    { term: "Wave-Particle Duality", def: "Matter and light show both wave and particle behavior.", subject: "Physics" },
    { term: "Heisenberg Uncertainty", def: "Position and momentum cannot both be known exactly.", subject: "Physics" },
    { term: "Special Relativity", def: "Speed of light constant; E = mc².", subject: "Physics" },
    { term: "Archimedes' Principle", def: "Buoyant force equals weight of displaced fluid.", subject: "Physics" },
    { term: "Bernoulli's Principle", def: "Faster-moving fluid exerts less pressure.", subject: "Physics" },
    { term: "First Law of Thermodynamics", def: "Energy is conserved; ΔU = Q − W.", subject: "Physics" },
    { term: "Second Law of Thermodynamics", def: "Entropy of isolated system always increases.", subject: "Physics" },
    { term: "Specific Heat", def: "Energy to raise 1 kg of substance by 1°C.", subject: "Physics" },
    { term: "Carnot Efficiency", def: "Maximum heat engine efficiency; 1 − T_cold/T_hot.", subject: "Physics" },
    { term: "Gravitational Force", def: "F = Gm₁m₂/r²; inverse square law.", subject: "Physics" },
    { term: "Centripetal Acceleration", def: "Acceleration toward center of circular path; a = v²/r.", subject: "Physics" },
    { term: "Torque", def: "Rotational force; τ = r × F.", subject: "Physics" },
    { term: "Angular Momentum", def: "Rotational analog of linear momentum; conserved.", subject: "Physics" },
    { term: "Electric Flux", def: "Measure of electric field through a surface area.", subject: "Physics" },
    { term: "Gauss's Law", def: "Net electric flux equals enclosed charge divided by ε₀.", subject: "Physics" },
    { term: "Magnetic Force", def: "F = qv × B; force on moving charge in magnetic field.", subject: "Physics" },
    { term: "Index of Refraction", def: "n = c/v; ratio of light speed in vacuum to medium.", subject: "Physics" },
    { term: "Standing Wave", def: "Pattern of constructive/destructive interference at fixed points.", subject: "Physics" },
    { term: "Photoelectric Threshold", def: "Minimum frequency to eject electrons from metal.", subject: "Physics" },
    { term: "Escape Velocity", def: "Minimum speed to escape gravitational pull of body.", subject: "Physics" },

    // ── EARTH SCIENCE (55) ────────────────────────────────────────────────────
    { term: "Plate Tectonics", def: "Earth's crust divided into moving plates.", subject: "Earth Science" },
    { term: "Continental Drift", def: "Continents have moved over geological time.", subject: "Earth Science" },
    { term: "Seafloor Spreading", def: "New crust forms at mid-ocean ridges.", subject: "Earth Science" },
    { term: "Subduction", def: "Denser oceanic plate sinks beneath lighter plate.", subject: "Earth Science" },
    { term: "Divergent Boundary", def: "Plates move apart; new crust forms at ridge.", subject: "Earth Science" },
    { term: "Convergent Boundary", def: "Plates collide; mountains or trenches form.", subject: "Earth Science" },
    { term: "Transform Boundary", def: "Plates slide horizontally past each other.", subject: "Earth Science" },
    { term: "P-Waves", def: "Compressional seismic waves; travel through solid and liquid.", subject: "Earth Science" },
    { term: "S-Waves", def: "Shear seismic waves; travel only through solid.", subject: "Earth Science" },
    { term: "Richter Scale", def: "Logarithmic scale measuring earthquake magnitude.", subject: "Earth Science" },
    { term: "Igneous Rock", def: "Formed from cooled magma or lava.", subject: "Earth Science" },
    { term: "Sedimentary Rock", def: "Formed from compressed sediment layers.", subject: "Earth Science" },
    { term: "Metamorphic Rock", def: "Existing rock changed by heat and pressure.", subject: "Earth Science" },
    { term: "Rock Cycle", def: "Continuous transformation among igneous, sedimentary, metamorphic.", subject: "Earth Science" },
    { term: "Weathering", def: "Breaking down rocks by physical or chemical processes.", subject: "Earth Science" },
    { term: "Erosion", def: "Transport of weathered material by wind, water, or ice.", subject: "Earth Science" },
    { term: "Deposition", def: "Settling of eroded material at new location.", subject: "Earth Science" },
    { term: "Relative Dating", def: "Determining age from rock layer position.", subject: "Earth Science" },
    { term: "Radiometric Dating", def: "Using radioactive decay to find absolute rock age.", subject: "Earth Science" },
    { term: "Half-Life", def: "Time for half of radioactive sample to decay.", subject: "Earth Science" },
    { term: "Troposphere", def: "Lowest atmospheric layer; where weather occurs.", subject: "Earth Science" },
    { term: "Stratosphere", def: "Contains ozone layer; absorbs UV radiation.", subject: "Earth Science" },
    { term: "Greenhouse Effect", def: "Atmospheric gases trap heat, warming Earth's surface.", subject: "Earth Science" },
    { term: "El Niño", def: "Periodic warming of Pacific Ocean disrupting global weather.", subject: "Earth Science" },
    { term: "Thermohaline Circulation", def: "Global ocean conveyor belt driven by density differences.", subject: "Earth Science" },
    { term: "Water Cycle", def: "Evaporation, condensation, and precipitation cycle of water.", subject: "Earth Science" },
    { term: "Kepler's Laws", def: "Planets orbit in ellipses; speed varies with distance from Sun.", subject: "Earth Science" },
    { term: "H-R Diagram", def: "Graph of stellar luminosity vs. temperature classifying stars.", subject: "Earth Science" },
    { term: "Stellar Evolution", def: "Stars form in nebula, live on main sequence, then die.", subject: "Earth Science" },
    { term: "Supernova", def: "Explosive death of a massive star.", subject: "Earth Science" },
    { term: "Black Hole", def: "Object with gravity so strong light cannot escape.", subject: "Earth Science" },
    { term: "Big Bang Theory", def: "Universe began ~13.8 billion years ago from a singularity.", subject: "Earth Science" },
    { term: "Hubble's Law", def: "Galaxies recede faster the farther they are.", subject: "Earth Science" },
    { term: "Coriolis Effect", def: "Deflection of air and water due to Earth's rotation.", subject: "Earth Science" },
    { term: "Jet Stream", def: "Fast air current in upper troposphere steering weather.", subject: "Earth Science" },
    { term: "Soil Horizons", def: "Layers of soil from surface (A) through bedrock (R).", subject: "Earth Science" },
    { term: "Convection Currents", def: "Heat-driven circulation in Earth's mantle driving plates.", subject: "Earth Science" },
    { term: "Mineral", def: "Natural inorganic solid with definite chemical composition.", subject: "Earth Science" },
    { term: "Mohs Scale", def: "Scale from 1–10 rating mineral hardness.", subject: "Earth Science" },
    { term: "Geologic Time Scale", def: "Earth's 4.6-billion-year history divided into eons and eras.", subject: "Earth Science" },
    { term: "Mass Extinction", def: "Rapid loss of majority of species in geological record.", subject: "Earth Science" },
    { term: "Ozone Layer", def: "Stratospheric layer blocking harmful UV radiation.", subject: "Earth Science" },
    { term: "Solar Wind", def: "Stream of charged particles from Sun affecting Earth.", subject: "Earth Science" },
    { term: "Tidal Forces", def: "Moon's gravity pulls ocean water creating tides.", subject: "Earth Science" },
    { term: "Aurora", def: "Light display from solar particles hitting atmosphere.", subject: "Earth Science" },
    { term: "Ocean Trench", def: "Deepest part of ocean; forms at subduction zones.", subject: "Earth Science" },
    { term: "Hot Spot Volcano", def: "Volcano over mantle plume unrelated to plate boundary.", subject: "Earth Science" },
    { term: "Isostasy", def: "Crust floating on mantle in gravitational balance.", subject: "Earth Science" },
    { term: "Precession", def: "Wobble of Earth's rotational axis over 26,000 years.", subject: "Earth Science" },
    { term: "Albedo", def: "Fraction of solar energy reflected by a surface.", subject: "Earth Science" },
    { term: "Milankovitch Cycles", def: "Earth's orbital variations driving ice age cycles.", subject: "Earth Science" },
    { term: "Paleoclimatology", def: "Study of ancient climates using ice cores and fossils.", subject: "Earth Science" },
    { term: "Seafloor Age", def: "Youngest at mid-ocean ridge; oldest near trenches.", subject: "Earth Science" },
    { term: "Mantle Plume", def: "Column of hot mantle rock rising toward surface.", subject: "Earth Science" },
    { term: "Accretion", def: "Building of planetesimals by collision and gravity.", subject: "Earth Science" },

    // ── ENERGY (50) ───────────────────────────────────────────────────────────
    { term: "Kinetic Energy", def: "Energy of motion; KE = ½mv².", subject: "Energy" },
    { term: "Potential Energy", def: "Stored energy based on position or chemical state.", subject: "Energy" },
    { term: "Chemical Energy", def: "Energy stored in molecular bonds.", subject: "Energy" },
    { term: "Thermal Energy", def: "Total kinetic energy of particles in a substance.", subject: "Energy" },
    { term: "Electrical Energy", def: "Energy from moving electric charges.", subject: "Energy" },
    { term: "Nuclear Energy", def: "Energy from fission or fusion of atomic nuclei.", subject: "Energy" },
    { term: "Radiant Energy", def: "Energy carried by electromagnetic waves.", subject: "Energy" },
    { term: "Conservation of Energy", def: "Energy cannot be created or destroyed; only transformed.", subject: "Energy" },
    { term: "Efficiency", def: "Useful energy output divided by total energy input.", subject: "Energy" },
    { term: "Fossil Fuels", def: "Coal, oil, and natural gas from ancient organisms.", subject: "Energy" },
    { term: "Combustion", def: "Burning fuel with oxygen releases heat and CO₂.", subject: "Energy" },
    { term: "Nuclear Fission", def: "Heavy nucleus splits releasing enormous energy.", subject: "Energy" },
    { term: "Nuclear Fusion", def: "Light nuclei combine releasing even more energy than fission.", subject: "Energy" },
    { term: "Radioactivity", def: "Unstable nuclei emit particles and energy.", subject: "Energy" },
    { term: "Solar Energy", def: "Energy from the Sun's electromagnetic radiation.", subject: "Energy" },
    { term: "Photovoltaic Cell", def: "Converts sunlight directly to electricity.", subject: "Energy" },
    { term: "Wind Energy", def: "Kinetic energy of wind driving turbine generators.", subject: "Energy" },
    { term: "Hydroelectric Power", def: "Falling water turns turbines to generate electricity.", subject: "Energy" },
    { term: "Geothermal Energy", def: "Heat from Earth's interior used to generate power.", subject: "Energy" },
    { term: "Biomass Energy", def: "Energy from burning or fermenting organic matter.", subject: "Energy" },
    { term: "Hydrogen Fuel Cell", def: "Converts H₂ and O₂ to electricity and water.", subject: "Energy" },
    { term: "Generator", def: "Converts mechanical energy to electrical energy.", subject: "Energy" },
    { term: "Electric Motor", def: "Converts electrical energy to mechanical energy.", subject: "Energy" },
    { term: "Heat Engine", def: "Converts thermal energy to mechanical work.", subject: "Energy" },
    { term: "Entropy", def: "Disorder increases in all real energy transfers.", subject: "Energy" },
    { term: "Carnot Engine", def: "Theoretical maximum-efficiency heat engine.", subject: "Energy" },
    { term: "Specific Heat Capacity", def: "Energy needed to raise 1 kg of material by 1°C.", subject: "Energy" },
    { term: "Heat Transfer", def: "Energy moving by conduction, convection, or radiation.", subject: "Energy" },
    { term: "Greenhouse Gases", def: "CO₂, CH₄, N₂O trapping heat in atmosphere.", subject: "Energy" },
    { term: "Carbon Footprint", def: "Total greenhouse gas emissions from an activity.", subject: "Energy" },
    { term: "Renewable Energy", def: "Energy from naturally replenished sources.", subject: "Energy" },
    { term: "Nonrenewable Energy", def: "Energy from finite resources that cannot be replaced quickly.", subject: "Energy" },
    { term: "Energy Density", def: "Energy stored per unit mass or volume of fuel.", subject: "Energy" },
    { term: "Power", def: "Rate of energy transfer; measured in watts.", subject: "Energy" },
    { term: "Kilowatt-Hour", def: "Unit of energy; 1 kW used for 1 hour.", subject: "Energy" },
    { term: "Superconductor", def: "Material with zero electrical resistance at low temperature.", subject: "Energy" },
    { term: "Smart Grid", def: "Digital electricity network optimizing energy distribution.", subject: "Energy" },
    { term: "Energy Storage", def: "Batteries, pumped hydro store energy for later use.", subject: "Energy" },
    { term: "Transformer", def: "Changes AC voltage using electromagnetic induction.", subject: "Energy" },
    { term: "Ohmic Heating", def: "Electrical energy lost as heat in resistors.", subject: "Energy" },
    { term: "OTEC", def: "Ocean Thermal Energy Conversion; uses temperature differences.", subject: "Energy" },
    { term: "Tidal Energy", def: "Energy harnessed from rising and falling ocean tides.", subject: "Energy" },
    { term: "Wave Energy", def: "Energy captured from ocean surface wave motion.", subject: "Energy" },
    { term: "Coal Gasification", def: "Converting coal to syngas for cleaner combustion.", subject: "Energy" },
    { term: "Carbon Capture", def: "Technology removing CO₂ from emissions before release.", subject: "Energy" },
    { term: "Net Metering", def: "Selling excess solar/wind power back to the grid.", subject: "Energy" },
    { term: "Fracking", def: "High-pressure fluid injected to extract shale gas or oil.", subject: "Energy" },
    { term: "Energy Poverty", def: "Lack of access to reliable, affordable energy services.", subject: "Energy" },
    { term: "Levelized Cost", def: "Lifetime cost of power plant per unit energy generated.", subject: "Energy" },
    { term: "Peak Demand", def: "Highest point of electricity consumption in a period.", subject: "Energy" },

    // ── MATH (50) ─────────────────────────────────────────────────────────────
    { term: "Function", def: "Rule mapping each input to exactly one output.", subject: "Math" },
    { term: "Domain", def: "Set of all valid inputs for a function.", subject: "Math" },
    { term: "Range", def: "Set of all output values of a function.", subject: "Math" },
    { term: "Inverse Function", def: "Reverses the mapping of the original function; f⁻¹.", subject: "Math" },
    { term: "Composite Function", def: "f(g(x)); applying one function inside another.", subject: "Math" },
    { term: "Quadratic Formula", def: "x = (−b ± √(b²−4ac)) / 2a; solves ax²+bx+c=0.", subject: "Math" },
    { term: "Exponential Function", def: "f(x) = aˣ; constant ratio between successive outputs.", subject: "Math" },
    { term: "Logarithm", def: "Inverse of exponentiation; log_b(x) = y means bʸ = x.", subject: "Math" },
    { term: "Euler's Number", def: "e ≈ 2.718; base of natural logarithm.", subject: "Math" },
    { term: "Arithmetic Sequence", def: "Constant difference between consecutive terms.", subject: "Math" },
    { term: "Geometric Sequence", def: "Constant ratio between consecutive terms.", subject: "Math" },
    { term: "Binomial Theorem", def: "Expansion of (a + b)ⁿ using Pascal's triangle.", subject: "Math" },
    { term: "Permutation", def: "Ordered arrangement of items; nPr = n!/(n−r)!.", subject: "Math" },
    { term: "Combination", def: "Unordered selection of items; nCr = n!/r!(n−r)!.", subject: "Math" },
    { term: "Conditional Probability", def: "P(A|B); probability of A given that B occurred.", subject: "Math" },
    { term: "Sine", def: "Opposite over hypotenuse in right triangle; sin θ.", subject: "Math" },
    { term: "Cosine", def: "Adjacent over hypotenuse in right triangle; cos θ.", subject: "Math" },
    { term: "Tangent", def: "Opposite over adjacent; tan θ = sin θ / cos θ.", subject: "Math" },
    { term: "Unit Circle", def: "Circle of radius 1 used to define trig functions.", subject: "Math" },
    { term: "Law of Sines", def: "a/sin A = b/sin B = c/sin C for any triangle.", subject: "Math" },
    { term: "Law of Cosines", def: "c² = a² + b² − 2ab cos C for any triangle.", subject: "Math" },
    { term: "Radian", def: "Angle unit; 2π radians = 360°.", subject: "Math" },
    { term: "Derivative", def: "Rate of change; slope of tangent line at a point.", subject: "Math" },
    { term: "Integral", def: "Area under curve; antiderivative of a function.", subject: "Math" },
    { term: "Fundamental Theorem of Calculus", def: "Differentiation and integration are inverse operations.", subject: "Math" },
    { term: "Chain Rule", def: "d/dx[f(g(x))] = f′(g(x))·g′(x).", subject: "Math" },
    { term: "Product Rule", def: "d/dx[f·g] = f·g′ + g·f′.", subject: "Math" },
    { term: "Quotient Rule", def: "d/dx[f/g] = (g·f′ − f·g′) / g².", subject: "Math" },
    { term: "Matrix", def: "Rectangular array of numbers used in linear algebra.", subject: "Math" },
    { term: "Determinant", def: "Scalar value of a square matrix; used to solve systems.", subject: "Math" },
    { term: "Vector", def: "Quantity with both magnitude and direction.", subject: "Math" },
    { term: "Dot Product", def: "Scalar result of multiplying two vectors; a·b = |a||b|cosθ.", subject: "Math" },
    { term: "Standard Deviation", def: "Measure of spread around the mean in data set.", subject: "Math" },
    { term: "Normal Distribution", def: "Bell-shaped probability curve; symmetric about mean.", subject: "Math" },
    { term: "Correlation", def: "Statistical measure of linear relationship between variables.", subject: "Math" },
    { term: "Limit", def: "Value a function approaches as input approaches a value.", subject: "Math" },
    { term: "Asymptote", def: "Line that a curve approaches but never reaches.", subject: "Math" },
    { term: "Complex Number", def: "Number with real and imaginary parts; a + bi.", subject: "Math" },
    { term: "Imaginary Unit", def: "i = √(−1); basis of complex numbers.", subject: "Math" },
    { term: "Polynomial", def: "Sum of terms with non-negative integer exponents.", subject: "Math" },
    { term: "Rational Function", def: "Ratio of two polynomials; p(x)/q(x).", subject: "Math" },
    { term: "Absolute Value", def: "Distance from zero on number line; always non-negative.", subject: "Math" },
    { term: "Series Convergence", def: "Infinite series approaches finite sum as terms added.", subject: "Math" },
    { term: "Taylor Series", def: "Function expressed as infinite polynomial about a point.", subject: "Math" },
    { term: "Parametric Equations", def: "x and y expressed as functions of third variable t.", subject: "Math" },
    { term: "Polar Coordinates", def: "Position given as (r, θ) instead of (x, y).", subject: "Math" },
    { term: "Conic Sections", def: "Parabola, ellipse, hyperbola from slicing a cone.", subject: "Math" },
    { term: "Regression", def: "Line of best fit minimizing squared error from data.", subject: "Math" },
    { term: "Hypothesis Testing", def: "Statistical test of claim using sample data and p-value.", subject: "Math" },
    { term: "Eigenvalue", def: "Scalar λ where matrix A times vector v equals λv.", subject: "Math" }
  ],

  MS: [
    // ── BIOLOGY (60) ──────────────────────────────────────────────────────────
    { term: "Cell", def: "Basic unit of life.", subject: "Biology" },
    { term: "Cell Membrane", def: "Controls what enters and exits the cell.", subject: "Biology" },
    { term: "Cell Wall", def: "Rigid protective layer outside plant cell membranes.", subject: "Biology" },
    { term: "Nucleus", def: "Controls cell activities and contains DNA.", subject: "Biology" },
    { term: "Mitochondria", def: "Organelle that produces energy for the cell.", subject: "Biology" },
    { term: "Chloroplast", def: "Makes food using sunlight in plant cells.", subject: "Biology" },
    { term: "Ribosome", def: "Makes proteins inside the cell.", subject: "Biology" },
    { term: "Vacuole", def: "Storage space for water and nutrients inside cell.", subject: "Biology" },
    { term: "Lysosome", def: "Digests waste and old cell parts.", subject: "Biology" },
    { term: "Prokaryote", def: "Cell without a true nucleus; bacteria.", subject: "Biology" },
    { term: "Eukaryote", def: "Cell with a true membrane-bound nucleus.", subject: "Biology" },
    { term: "Photosynthesis", def: "Plants make food using sunlight, CO₂, and water.", subject: "Biology" },
    { term: "Cellular Respiration", def: "Breaking down food molecules to release energy.", subject: "Biology" },
    { term: "Glucose", def: "Simple sugar that is the main fuel for cells.", subject: "Biology" },
    { term: "Oxygen", def: "Gas used in respiration; released by photosynthesis.", subject: "Biology" },
    { term: "Carbon Dioxide", def: "Gas used in photosynthesis; released in respiration.", subject: "Biology" },
    { term: "Mitosis", def: "Cell divides to produce two identical daughter cells.", subject: "Biology" },
    { term: "Meiosis", def: "Cell divides to form sex cells with half chromosomes.", subject: "Biology" },
    { term: "DNA", def: "Molecule carrying all genetic information.", subject: "Biology" },
    { term: "Gene", def: "Segment of DNA that controls a specific trait.", subject: "Biology" },
    { term: "Chromosome", def: "Coiled structure of DNA found in nucleus.", subject: "Biology" },
    { term: "Dominant Trait", def: "Trait that shows when only one copy is present.", subject: "Biology" },
    { term: "Recessive Trait", def: "Trait that only shows when two copies are present.", subject: "Biology" },
    { term: "Heredity", def: "Passing of traits from parents to offspring.", subject: "Biology" },
    { term: "Mutation", def: "Change in the DNA sequence of an organism.", subject: "Biology" },
    { term: "Natural Selection", def: "Better-adapted organisms survive and reproduce more.", subject: "Biology" },
    { term: "Adaptation", def: "Trait helping an organism survive in its environment.", subject: "Biology" },
    { term: "Evolution", def: "Gradual change in species over many generations.", subject: "Biology" },
    { term: "Ecosystem", def: "All living things and their environment in an area.", subject: "Biology" },
    { term: "Food Chain", def: "Series of organisms each eating the one before it.", subject: "Biology" },
    { term: "Predator", def: "Animal that hunts and eats other animals.", subject: "Biology" },
    { term: "Prey", def: "Animal that is hunted and eaten by predators.", subject: "Biology" },
    { term: "Producer", def: "Organism making its own food via photosynthesis.", subject: "Biology" },
    { term: "Consumer", def: "Organism that eats other organisms for energy.", subject: "Biology" },
    { term: "Decomposer", def: "Organism breaking down dead material into nutrients.", subject: "Biology" },
    { term: "Habitat", def: "Place where an organism naturally lives.", subject: "Biology" },
    { term: "Population", def: "All individuals of the same species in an area.", subject: "Biology" },
    { term: "Community", def: "All populations living and interacting in an area.", subject: "Biology" },
    { term: "Biome", def: "Large region with a similar climate and organisms.", subject: "Biology" },
    { term: "Classification", def: "Grouping organisms by shared characteristics.", subject: "Biology" },
    { term: "Kingdom", def: "Broadest level of classification; e.g., Animalia.", subject: "Biology" },
    { term: "Species", def: "Group of organisms that can reproduce together.", subject: "Biology" },
    { term: "Virus", def: "Non-living particle that hijacks host cells to replicate.", subject: "Biology" },
    { term: "Bacteria", def: "Single-celled prokaryote organisms.", subject: "Biology" },
    { term: "Fungi", def: "Kingdom of decomposers including mushrooms and molds.", subject: "Biology" },
    { term: "Osmosis", def: "Water moving across membrane toward higher solute.", subject: "Biology" },
    { term: "Diffusion", def: "Molecules moving from high to low concentration.", subject: "Biology" },
    { term: "Enzyme", def: "Protein that speeds up chemical reactions.", subject: "Biology" },
    { term: "Immune System", def: "Body's defense system against pathogens.", subject: "Biology" },
    { term: "Vaccine", def: "Trains immune system to fight specific disease.", subject: "Biology" },
    { term: "Vertebrate", def: "Animal with a backbone.", subject: "Biology" },
    { term: "Invertebrate", def: "Animal without a backbone.", subject: "Biology" },
    { term: "Mammal", def: "Warm-blooded vertebrate with hair that nurses young.", subject: "Biology" },
    { term: "Reptile", def: "Cold-blooded vertebrate with scales.", subject: "Biology" },
    { term: "Amphibian", def: "Vertebrate living in both water and on land.", subject: "Biology" },
    { term: "Homeostasis", def: "Keeping internal body conditions stable.", subject: "Biology" },
    { term: "Nervous System", def: "Brain, spinal cord, and nerves controlling body.", subject: "Biology" },
    { term: "Hormone", def: "Chemical messenger controlling body functions.", subject: "Biology" },
    { term: "Photosynthesis Equation", def: "6CO₂ + 6H₂O + light → C₆H₁₂O₆ + 6O₂.", subject: "Biology" },
    { term: "Food Web", def: "Overlapping food chains showing feeding in ecosystem.", subject: "Biology" },

    // ── CHEMISTRY (55) ────────────────────────────────────────────────────────
    { term: "Matter", def: "Anything with mass and volume.", subject: "Chemistry" },
    { term: "Atom", def: "Smallest particle of an element.", subject: "Chemistry" },
    { term: "Element", def: "Pure substance made of one type of atom.", subject: "Chemistry" },
    { term: "Compound", def: "Two or more elements chemically combined.", subject: "Chemistry" },
    { term: "Mixture", def: "Two or more substances physically combined.", subject: "Chemistry" },
    { term: "Proton", def: "Positive particle found in atomic nucleus.", subject: "Chemistry" },
    { term: "Neutron", def: "Neutral particle found in atomic nucleus.", subject: "Chemistry" },
    { term: "Electron", def: "Negative particle orbiting the nucleus.", subject: "Chemistry" },
    { term: "Atomic Number", def: "Number of protons in an atom.", subject: "Chemistry" },
    { term: "Mass Number", def: "Number of protons plus neutrons in nucleus.", subject: "Chemistry" },
    { term: "Periodic Table", def: "Chart organizing elements by atomic number.", subject: "Chemistry" },
    { term: "Metal", def: "Shiny element conducting heat and electricity.", subject: "Chemistry" },
    { term: "Nonmetal", def: "Element that is a poor conductor.", subject: "Chemistry" },
    { term: "Metalloid", def: "Element with properties of both metals and nonmetals.", subject: "Chemistry" },
    { term: "Chemical Symbol", def: "One or two-letter abbreviation for an element.", subject: "Chemistry" },
    { term: "Molecule", def: "Two or more atoms bonded together.", subject: "Chemistry" },
    { term: "Ion", def: "Atom with a positive or negative charge.", subject: "Chemistry" },
    { term: "Ionic Compound", def: "Metal and nonmetal bonded by electron transfer.", subject: "Chemistry" },
    { term: "Covalent Compound", def: "Nonmetals sharing electrons in bonds.", subject: "Chemistry" },
    { term: "Chemical Formula", def: "Symbols showing the atoms in a compound.", subject: "Chemistry" },
    { term: "Chemical Reaction", def: "Process rearranging atoms into new substances.", subject: "Chemistry" },
    { term: "Reactant", def: "Starting material in a chemical reaction.", subject: "Chemistry" },
    { term: "Product", def: "Substance formed in a chemical reaction.", subject: "Chemistry" },
    { term: "Conservation of Mass", def: "Mass is neither created nor destroyed in reactions.", subject: "Chemistry" },
    { term: "Physical Change", def: "Change in form without changing chemical composition.", subject: "Chemistry" },
    { term: "Chemical Change", def: "Change producing new substances with different properties.", subject: "Chemistry" },
    { term: "Acid", def: "Substance with pH below 7; tastes sour.", subject: "Chemistry" },
    { term: "Base", def: "Substance with pH above 7; feels slippery.", subject: "Chemistry" },
    { term: "pH Scale", def: "0–14 scale measuring acidity; 7 is neutral.", subject: "Chemistry" },
    { term: "Solute", def: "Substance that gets dissolved in a solution.", subject: "Chemistry" },
    { term: "Solvent", def: "Substance doing the dissolving in a solution.", subject: "Chemistry" },
    { term: "Solution", def: "Uniform mixture of solute dissolved in solvent.", subject: "Chemistry" },
    { term: "Concentration", def: "Amount of solute in a given volume of solution.", subject: "Chemistry" },
    { term: "Density", def: "Mass per unit volume; D = m/V.", subject: "Chemistry" },
    { term: "Boiling Point", def: "Temperature at which liquid becomes gas.", subject: "Chemistry" },
    { term: "Melting Point", def: "Temperature at which solid becomes liquid.", subject: "Chemistry" },
    { term: "Evaporation", def: "Liquid changing to gas below boiling point.", subject: "Chemistry" },
    { term: "Condensation", def: "Gas changing to liquid.", subject: "Chemistry" },
    { term: "States of Matter", def: "Solid, liquid, gas, and plasma.", subject: "Chemistry" },
    { term: "Kinetic Theory", def: "All particles are in constant motion.", subject: "Chemistry" },
    { term: "Endothermic Reaction", def: "Reaction absorbing heat from surroundings.", subject: "Chemistry" },
    { term: "Exothermic Reaction", def: "Reaction releasing heat to surroundings.", subject: "Chemistry" },
    { term: "Catalyst", def: "Speeds up a reaction without being used up.", subject: "Chemistry" },
    { term: "Combustion", def: "Burning; reaction with oxygen producing heat and light.", subject: "Chemistry" },
    { term: "Corrosion", def: "Metal reacting with environment, e.g., rusting.", subject: "Chemistry" },
    { term: "Alloy", def: "Mixture of metals; e.g., steel = iron + carbon.", subject: "Chemistry" },
    { term: "Polymer", def: "Large molecule made of repeating smaller monomer units.", subject: "Chemistry" },
    { term: "Electrolyte", def: "Substance forming ions when dissolved in water.", subject: "Chemistry" },
    { term: "Valence Electrons", def: "Electrons in outermost shell; control bonding.", subject: "Chemistry" },
    { term: "Noble Gas", def: "Stable element with a full outer electron shell.", subject: "Chemistry" },
    { term: "Halogen", def: "Highly reactive nonmetal in group 17.", subject: "Chemistry" },
    { term: "Alkali Metal", def: "Very reactive metal in group 1 of periodic table.", subject: "Chemistry" },
    { term: "Isotope", def: "Same element with different number of neutrons.", subject: "Chemistry" },
    { term: "Precipitation", def: "Solid forming when two solutions are mixed.", subject: "Chemistry" },
    { term: "Oxidation", def: "Substance loses electrons or gains oxygen.", subject: "Chemistry" },

    // ── PHYSICS (55) ──────────────────────────────────────────────────────────
    { term: "Force", def: "A push or pull on an object.", subject: "Physics" },
    { term: "Net Force", def: "Sum of all forces acting on an object.", subject: "Physics" },
    { term: "Newton", def: "Unit of force in the metric system.", subject: "Physics" },
    { term: "Gravity", def: "Force pulling objects with mass toward each other.", subject: "Physics" },
    { term: "Friction", def: "Force opposing motion between two surfaces.", subject: "Physics" },
    { term: "Normal Force", def: "Surface pushing back perpendicular to object.", subject: "Physics" },
    { term: "Acceleration", def: "Rate of change of velocity.", subject: "Physics" },
    { term: "Velocity", def: "Speed in a specific direction.", subject: "Physics" },
    { term: "Speed", def: "Distance traveled per unit of time.", subject: "Physics" },
    { term: "Mass", def: "Amount of matter in object; kilograms.", subject: "Physics" },
    { term: "Weight", def: "Gravitational force on an object.", subject: "Physics" },
    { term: "Newton's First Law", def: "Objects stay at rest or in motion without net force.", subject: "Physics" },
    { term: "Newton's Second Law", def: "F = ma; force equals mass times acceleration.", subject: "Physics" },
    { term: "Newton's Third Law", def: "Every action force has equal and opposite reaction.", subject: "Physics" },
    { term: "Inertia", def: "Tendency to resist any change in motion.", subject: "Physics" },
    { term: "Momentum", def: "Mass times velocity of a moving object.", subject: "Physics" },
    { term: "Work", def: "Force times distance in direction of force.", subject: "Physics" },
    { term: "Energy", def: "Ability to do work or cause change.", subject: "Physics" },
    { term: "Kinetic Energy", def: "Energy an object has due to its motion.", subject: "Physics" },
    { term: "Potential Energy", def: "Stored energy based on position.", subject: "Physics" },
    { term: "Conservation of Energy", def: "Total energy in a system stays constant.", subject: "Physics" },
    { term: "Power", def: "Rate of doing work; work divided by time.", subject: "Physics" },
    { term: "Simple Machine", def: "Device making work easier; lever, pulley, ramp.", subject: "Physics" },
    { term: "Mechanical Advantage", def: "Output force divided by input force.", subject: "Physics" },
    { term: "Lever", def: "Rigid bar rotating on a fixed pivot point.", subject: "Physics" },
    { term: "Pulley", def: "Wheel with rope used to lift heavy objects.", subject: "Physics" },
    { term: "Inclined Plane", def: "Ramp spreading force over longer distance.", subject: "Physics" },
    { term: "Wave", def: "Transfer of energy without transfer of matter.", subject: "Physics" },
    { term: "Transverse Wave", def: "Vibration perpendicular to direction of wave travel.", subject: "Physics" },
    { term: "Longitudinal Wave", def: "Vibration parallel to direction of wave travel.", subject: "Physics" },
    { term: "Amplitude", def: "Height of wave from rest; related to energy.", subject: "Physics" },
    { term: "Wavelength", def: "Distance between two consecutive wave crests.", subject: "Physics" },
    { term: "Frequency", def: "Number of waves passing a point per second; hertz.", subject: "Physics" },
    { term: "Sound Wave", def: "Mechanical wave needing a medium to travel.", subject: "Physics" },
    { term: "Light Wave", def: "Electromagnetic wave; travels without a medium.", subject: "Physics" },
    { term: "Reflection", def: "Light bouncing off a surface.", subject: "Physics" },
    { term: "Refraction", def: "Light bending when entering a new medium.", subject: "Physics" },
    { term: "Electromagnetic Spectrum", def: "All types of radiation ordered by frequency.", subject: "Physics" },
    { term: "Electric Charge", def: "Property of matter; positive or negative.", subject: "Physics" },
    { term: "Static Electricity", def: "Buildup of electric charge on a surface.", subject: "Physics" },
    { term: "Electric Current", def: "Flow of electric charge; measured in amperes.", subject: "Physics" },
    { term: "Voltage", def: "Electrical pressure pushing current; measured in volts.", subject: "Physics" },
    { term: "Resistance", def: "Opposition to current flow; measured in ohms.", subject: "Physics" },
    { term: "Circuit", def: "Complete path for electric current to flow.", subject: "Physics" },
    { term: "Series Circuit", def: "One path for current through all components.", subject: "Physics" },
    { term: "Parallel Circuit", def: "Multiple paths so current splits between components.", subject: "Physics" },
    { term: "Magnet", def: "Object creating a magnetic field.", subject: "Physics" },
    { term: "Electromagnetism", def: "Link between electricity and magnetism.", subject: "Physics" },
    { term: "Temperature", def: "Measure of average kinetic energy of particles.", subject: "Physics" },
    { term: "Heat", def: "Thermal energy transferred between objects.", subject: "Physics" },
    { term: "Conduction", def: "Heat transfer through direct contact between objects.", subject: "Physics" },
    { term: "Convection", def: "Heat transfer through movement of fluid.", subject: "Physics" },
    { term: "Radiation", def: "Heat transfer through electromagnetic waves.", subject: "Physics" },
    { term: "Ohm's Law", def: "V = IR; voltage equals current times resistance.", subject: "Physics" },
    { term: "Density", def: "Mass per unit volume of a substance.", subject: "Physics" },

    // ── EARTH SCIENCE (55) ────────────────────────────────────────────────────
    { term: "Earth's Layers", def: "Crust, mantle, outer core, inner core from surface to center.", subject: "Earth Science" },
    { term: "Crust", def: "Thin outermost layer of Earth.", subject: "Earth Science" },
    { term: "Mantle", def: "Thick rocky layer between crust and core.", subject: "Earth Science" },
    { term: "Core", def: "Center of Earth; liquid outer, solid inner iron.", subject: "Earth Science" },
    { term: "Plate Tectonics", def: "Earth's crust broken into moving plates.", subject: "Earth Science" },
    { term: "Fault", def: "Crack in Earth's crust where movement occurs.", subject: "Earth Science" },
    { term: "Earthquake", def: "Ground shaking from sudden plate movement.", subject: "Earth Science" },
    { term: "Volcano", def: "Opening releasing magma from Earth's interior.", subject: "Earth Science" },
    { term: "Magma", def: "Molten rock found underground.", subject: "Earth Science" },
    { term: "Lava", def: "Magma that has reached Earth's surface.", subject: "Earth Science" },
    { term: "Erosion", def: "Wearing away and moving rock or soil.", subject: "Earth Science" },
    { term: "Weathering", def: "Breaking rocks into smaller pieces by physical or chemical means.", subject: "Earth Science" },
    { term: "Deposition", def: "Eroded material settling in a new location.", subject: "Earth Science" },
    { term: "Igneous Rock", def: "Rock formed from cooled magma or lava.", subject: "Earth Science" },
    { term: "Sedimentary Rock", def: "Rock formed from compressed layers of sediment.", subject: "Earth Science" },
    { term: "Metamorphic Rock", def: "Rock changed by heat and pressure.", subject: "Earth Science" },
    { term: "Rock Cycle", def: "Rocks continuously transforming among three rock types.", subject: "Earth Science" },
    { term: "Fossil", def: "Preserved remains or traces of an ancient organism.", subject: "Earth Science" },
    { term: "Mineral", def: "Naturally occurring inorganic solid with definite composition.", subject: "Earth Science" },
    { term: "Soil", def: "Mixture of weathered rock and organic matter.", subject: "Earth Science" },
    { term: "Atmosphere", def: "Layers of gas surrounding Earth.", subject: "Earth Science" },
    { term: "Weather", def: "Short-term atmospheric conditions in a location.", subject: "Earth Science" },
    { term: "Climate", def: "Average weather of a region over a long time.", subject: "Earth Science" },
    { term: "Precipitation", def: "Water falling from atmosphere: rain, snow, or sleet.", subject: "Earth Science" },
    { term: "Evaporation", def: "Liquid water changing into water vapor.", subject: "Earth Science" },
    { term: "Water Cycle", def: "Continuous movement of water through environment.", subject: "Earth Science" },
    { term: "Groundwater", def: "Water stored underground in soil and rock.", subject: "Earth Science" },
    { term: "Ocean", def: "Large body of saltwater covering most of Earth.", subject: "Earth Science" },
    { term: "Tide", def: "Rise and fall of ocean level caused by Moon's gravity.", subject: "Earth Science" },
    { term: "Current", def: "Flow of water moving in a specific direction.", subject: "Earth Science" },
    { term: "Cloud", def: "Water droplets or ice crystals suspended in air.", subject: "Earth Science" },
    { term: "Humidity", def: "Amount of water vapor in the air.", subject: "Earth Science" },
    { term: "Air Pressure", def: "Weight of atmosphere pushing down on surface.", subject: "Earth Science" },
    { term: "Wind", def: "Movement of air from high to low pressure.", subject: "Earth Science" },
    { term: "Front", def: "Boundary between air masses of different temperatures.", subject: "Earth Science" },
    { term: "Greenhouse Effect", def: "Gases trapping heat from Sun in atmosphere.", subject: "Earth Science" },
    { term: "Global Warming", def: "Rise in Earth's average surface temperature.", subject: "Earth Science" },
    { term: "Ozone Layer", def: "Atmospheric layer blocking harmful UV radiation.", subject: "Earth Science" },
    { term: "Fossil Record", def: "Evidence of past life preserved in rock layers.", subject: "Earth Science" },
    { term: "Relative Dating", def: "Using rock layers to determine relative age.", subject: "Earth Science" },
    { term: "Solar System", def: "Sun and all objects orbiting it.", subject: "Earth Science" },
    { term: "Planet", def: "Large body orbiting star that cleared its orbit.", subject: "Earth Science" },
    { term: "Moon", def: "Natural satellite orbiting a planet.", subject: "Earth Science" },
    { term: "Star", def: "Massive ball of plasma undergoing nuclear fusion.", subject: "Earth Science" },
    { term: "Sun", def: "Earth's star; source of light and heat.", subject: "Earth Science" },
    { term: "Galaxy", def: "Collection of billions of stars bound by gravity.", subject: "Earth Science" },
    { term: "Orbit", def: "Path of one object around another due to gravity.", subject: "Earth Science" },
    { term: "Rotation", def: "Spinning on axis; causes day and night.", subject: "Earth Science" },
    { term: "Revolution", def: "Orbit around another object; causes seasons.", subject: "Earth Science" },
    { term: "Season", def: "Temperature pattern caused by Earth's axial tilt.", subject: "Earth Science" },
    { term: "Constellation", def: "Pattern of stars forming a picture in the sky.", subject: "Earth Science" },
    { term: "Eclipse", def: "Shadow of one body blocking light to another.", subject: "Earth Science" },
    { term: "Comet", def: "Icy body with tail of gas when near Sun.", subject: "Earth Science" },
    { term: "Asteroid", def: "Rocky body orbiting the Sun; mostly in asteroid belt.", subject: "Earth Science" },
    { term: "Meteorite", def: "Space rock that reaches Earth's surface.", subject: "Earth Science" },
    { term: "Light-Year", def: "Distance light travels in one year.", subject: "Earth Science" },

    // ── ENERGY (50) ───────────────────────────────────────────────────────────
    { term: "Energy", def: "Ability to do work or cause change.", subject: "Energy" },
    { term: "Kinetic Energy", def: "Energy an object has due to its motion.", subject: "Energy" },
    { term: "Potential Energy", def: "Stored energy based on position or condition.", subject: "Energy" },
    { term: "Gravitational PE", def: "Energy stored by height above the ground.", subject: "Energy" },
    { term: "Elastic PE", def: "Energy stored in a stretched or compressed object.", subject: "Energy" },
    { term: "Chemical Energy", def: "Energy stored in chemical bonds.", subject: "Energy" },
    { term: "Thermal Energy", def: "Heat energy; total motion of all particles.", subject: "Energy" },
    { term: "Light Energy", def: "Energy carried by light waves.", subject: "Energy" },
    { term: "Sound Energy", def: "Energy carried by sound waves.", subject: "Energy" },
    { term: "Electrical Energy", def: "Energy from moving electrons.", subject: "Energy" },
    { term: "Nuclear Energy", def: "Energy from the atomic nucleus.", subject: "Energy" },
    { term: "Energy Transformation", def: "Changing from one energy form to another.", subject: "Energy" },
    { term: "Conservation of Energy", def: "Energy cannot be created or destroyed.", subject: "Energy" },
    { term: "Fossil Fuels", def: "Coal, oil, and natural gas; nonrenewable.", subject: "Energy" },
    { term: "Coal", def: "Solid fossil fuel formed from ancient plant matter.", subject: "Energy" },
    { term: "Petroleum", def: "Liquid fossil fuel extracted from underground.", subject: "Energy" },
    { term: "Natural Gas", def: "Gaseous fossil fuel; mostly methane.", subject: "Energy" },
    { term: "Renewable Energy", def: "Energy from naturally replenished sources.", subject: "Energy" },
    { term: "Solar Energy", def: "Energy captured from sunlight.", subject: "Energy" },
    { term: "Wind Energy", def: "Energy from moving air turning turbines.", subject: "Energy" },
    { term: "Hydroelectric Energy", def: "Electricity generated from falling or flowing water.", subject: "Energy" },
    { term: "Geothermal Energy", def: "Heat energy from inside Earth.", subject: "Energy" },
    { term: "Biomass", def: "Organic matter burned or fermented for fuel.", subject: "Energy" },
    { term: "Nuclear Power", def: "Electricity generated from nuclear fission.", subject: "Energy" },
    { term: "Generator", def: "Machine converting motion into electricity.", subject: "Energy" },
    { term: "Turbine", def: "Spinning machine converting fluid motion to rotation.", subject: "Energy" },
    { term: "Solar Panel", def: "Device converting sunlight into electricity.", subject: "Energy" },
    { term: "Insulation", def: "Material that slows heat transfer.", subject: "Energy" },
    { term: "Conductor", def: "Material allowing energy to flow easily through it.", subject: "Energy" },
    { term: "Insulator", def: "Material blocking the flow of energy.", subject: "Energy" },
    { term: "Efficiency", def: "Useful output energy divided by total input energy.", subject: "Energy" },
    { term: "Wasted Energy", def: "Energy lost as unwanted heat or sound.", subject: "Energy" },
    { term: "Food Energy", def: "Chemical energy stored in food; measured in Calories.", subject: "Energy" },
    { term: "Calorie", def: "Unit of food energy.", subject: "Energy" },
    { term: "Joule", def: "Scientific unit of energy.", subject: "Energy" },
    { term: "Watt", def: "Unit of power; one joule per second.", subject: "Energy" },
    { term: "Power", def: "Rate of energy use or transfer.", subject: "Energy" },
    { term: "Battery", def: "Device storing chemical energy for later use.", subject: "Energy" },
    { term: "Heat", def: "Thermal energy transferred between objects.", subject: "Energy" },
    { term: "Conduction", def: "Heat moving through direct contact.", subject: "Energy" },
    { term: "Convection", def: "Heat moving through fluid circulation.", subject: "Energy" },
    { term: "Radiation", def: "Heat moving as electromagnetic waves.", subject: "Energy" },
    { term: "Carbon Dioxide", def: "Greenhouse gas released by burning fossil fuels.", subject: "Energy" },
    { term: "Greenhouse Gas", def: "Gas trapping heat in Earth's atmosphere.", subject: "Energy" },
    { term: "Climate Change", def: "Long-term changes in Earth's temperature and weather.", subject: "Energy" },
    { term: "Carbon Footprint", def: "Total greenhouse gas emissions from an activity.", subject: "Energy" },
    { term: "Energy Conservation", def: "Using less energy to reduce waste.", subject: "Energy" },
    { term: "Pollution", def: "Harmful substances released into environment.", subject: "Energy" },
    { term: "Nonrenewable", def: "Energy source that runs out and cannot be replaced quickly.", subject: "Energy" },
    { term: "Fuel Cell", def: "Converts fuel directly to electricity without burning.", subject: "Energy" },

    // ── MATH (50) ─────────────────────────────────────────────────────────────
    { term: "Whole Number", def: "Non-negative integer: 0, 1, 2, 3...", subject: "Math" },
    { term: "Integer", def: "Positive, negative, or zero whole numbers.", subject: "Math" },
    { term: "Fraction", def: "Part of a whole; numerator over denominator.", subject: "Math" },
    { term: "Decimal", def: "Number with digits after a decimal point.", subject: "Math" },
    { term: "Percent", def: "Rate per hundred; out of 100.", subject: "Math" },
    { term: "Ratio", def: "Comparison of two quantities by division.", subject: "Math" },
    { term: "Proportion", def: "Equation showing two ratios are equal.", subject: "Math" },
    { term: "Variable", def: "Letter representing an unknown number.", subject: "Math" },
    { term: "Expression", def: "Math phrase with numbers, variables, and operations.", subject: "Math" },
    { term: "Equation", def: "Math statement showing two things are equal.", subject: "Math" },
    { term: "Inequality", def: "Comparison using >, <, ≥, or ≤.", subject: "Math" },
    { term: "Order of Operations", def: "PEMDAS: parentheses, exponents, multiply/divide, add/subtract.", subject: "Math" },
    { term: "Exponent", def: "Number of times base is multiplied by itself.", subject: "Math" },
    { term: "Square Root", def: "Number that when squared gives the original number.", subject: "Math" },
    { term: "Prime Number", def: "Number divisible only by 1 and itself.", subject: "Math" },
    { term: "Composite Number", def: "Number with more than two factors.", subject: "Math" },
    { term: "Factor", def: "Number that divides evenly into another.", subject: "Math" },
    { term: "Multiple", def: "Product of a number and a whole number.", subject: "Math" },
    { term: "GCF", def: "Greatest common factor; largest shared factor of numbers.", subject: "Math" },
    { term: "LCM", def: "Least common multiple; smallest shared multiple.", subject: "Math" },
    { term: "Absolute Value", def: "Distance from zero; always non-negative.", subject: "Math" },
    { term: "Coordinate Plane", def: "Grid with x-axis and y-axis for plotting points.", subject: "Math" },
    { term: "Ordered Pair", def: "(x, y) coordinates of a point on a plane.", subject: "Math" },
    { term: "Slope", def: "Steepness of a line; rise divided by run.", subject: "Math" },
    { term: "y-Intercept", def: "Where a line crosses the y-axis.", subject: "Math" },
    { term: "Linear Equation", def: "Equation whose graph is a straight line.", subject: "Math" },
    { term: "Area", def: "Amount of space inside a 2D shape.", subject: "Math" },
    { term: "Perimeter", def: "Total distance around the outside of a shape.", subject: "Math" },
    { term: "Volume", def: "Amount of space inside a 3D shape.", subject: "Math" },
    { term: "Surface Area", def: "Total area of all faces of a 3D shape.", subject: "Math" },
    { term: "Angle", def: "Measure of rotation between two rays.", subject: "Math" },
    { term: "Right Angle", def: "Angle measuring exactly 90°.", subject: "Math" },
    { term: "Acute Angle", def: "Angle less than 90°.", subject: "Math" },
    { term: "Obtuse Angle", def: "Angle greater than 90° but less than 180°.", subject: "Math" },
    { term: "Triangle", def: "Polygon with three sides and three angles.", subject: "Math" },
    { term: "Quadrilateral", def: "Polygon with four sides.", subject: "Math" },
    { term: "Parallel Lines", def: "Lines that never intersect; same slope.", subject: "Math" },
    { term: "Perpendicular Lines", def: "Lines intersecting at exactly 90°.", subject: "Math" },
    { term: "Congruent", def: "Same size and same shape.", subject: "Math" },
    { term: "Similar", def: "Same shape but different size.", subject: "Math" },
    { term: "Mean", def: "Average; sum of values divided by count.", subject: "Math" },
    { term: "Median", def: "Middle value when data is ordered.", subject: "Math" },
    { term: "Mode", def: "Most frequently occurring value in data.", subject: "Math" },
    { term: "Range", def: "Difference between highest and lowest values.", subject: "Math" },
    { term: "Probability", def: "Likelihood of event; favorable outcomes / total outcomes.", subject: "Math" },
    { term: "Pythagorean Theorem", def: "a² + b² = c² for right triangles.", subject: "Math" },
    { term: "Rate", def: "Ratio comparing two different units.", subject: "Math" },
    { term: "Unit Rate", def: "Rate with a denominator of 1.", subject: "Math" },
    { term: "Scientific Notation", def: "Number written as coefficient × power of 10.", subject: "Math" },
    { term: "Distributive Property", def: "a(b + c) = ab + ac.", subject: "Math" }
  ]
};
