MSBiology = {
  "A diver finds an underwater cave filled with bacteria that seem to feed on volcanic sulfur vents. What type of organisms are these? W) Heterotroph X) Hemotroph Y) Chemotroph Z) Phototroph": "Chemotroph",
  "A liver cell has stopped functioning and a scientist observes that it is producing lactic acid. Failure of what organelle most likely caused the liver cell to stop functioning? W) Mitochondrion X) Nucleus Y) Ribosome Z) Golgi Body": "Mitochondrion",
  "The thin, upper fraction of the pelagic zone is known as what?": "Epipelagic zone",
  "What is the term for proteins that act as catalysts in chemical reactions?": "Enzymes",
  "In a human heart, through what structure does oxygenated blood first pass? W) Right Atrium X) Right Ventricle Y) Left Atrium Z) Left Ventricle": "Left Atrium",
  "Which of the major groups of plants contains no vasculature? W) Bryophytes X) Gymnosperms Y) Angiosperms Z) Embryophytes": "Bryophytes",
  "Which of the following is NOT a difference between archaeans and eubacteria? W) Archaeans have a nucleus, while eubacteria do not X) Eubacteria have peptidoglycan in their cell walls, while Archaeans do not Y) Archaeans can have introns, while eubacteria do not Z) Archaeans have several different RNA polymerases, while eubacteria have just one": "Archaeans have a nucleus, while eubacteria do not",
  "In mammals, what organ is composed of cardiac muscle tissue?": "Heart",
  "Which of the following types of enzymes would most likely be involved in adding a water molecule to a substrate? W) Transferase X) Hydrolase Y) Oxidoreductase Z) Lyase": "Hydrolase",
  "A liver cell is slowly dying because it can not break down toxins. What organelle is likely defective in this cell? W) Golgi complex X) Mitochondria Y) Ribosome Z) Endoplasmic reticulum": "Endoplasmic reticulum",
  "Which of the following terms best describes groups of rabbits, foxes, deer, and birds living in a temperate deciduous forest? W) Population X) Community Y) Habitat Z) Niche": "Community",
  "Most metabolic pathways in biology are regulated so that the product of a pathway inhibits the enzymes in that pathway. What is this inhibition scheme called?": "Negative feedback",
  "Which of the following types of joints can be found in the knuckles of a human index finger? W) Saddle X) Pivot Y) Gliding Z) Ellipsoid": "Ellipsoid",
  "What cellular organelle is responsible for forming proteins from amino acids?": "Ribosome",
  "What is the general term for cells that have half as many chromosomes as diploid cells?": "Haploid cells",
  "What is the term for chemicals that are used to transmit impulses from one neuron to another?": "Neurotransmitters",
  "What is the term for the point on a stem at which a leaf is attached?": "Node",
  "What is the term for an automatic response to a stimulus, such as sneezing or blinking?": "Reflex",
  "What region in the eukaryotic nucleus is the site of initial rRNA synthesis?": "Nucleolus",
  "What group of mammals lays eggs?": "Monotremes",
  "During what phase of mitosis do chromosomes line up in the middle of the cell?": "Metaphase",
  "Hirudinea is a class that contains which of the following organisms? W) Tapeworms X) Hagfish Y) Centipedes Z) Leeches": "Leeches",
  "The human eye focuses light through the lens onto what photosensitive structure?": "Retina",
  "Scientists at Los Alamos National Lab are studying a group of pumps associated with Gram-negative and Gram-positive organisms. These organisms are part of what domain?": "Eubacteria",
  "Which of the following best describes how fungi feed? W) They are chemoautotrophs X) They are photoautotrophs Y) They are heterotrophs Z) Some are photoautotrophs, while others are chemoautotrophs": "They are heterotrophs",
  "What is the adjective for the part of the human nervous system that is divided into the sensory division and the motor division?": "Peripheral"
};
MSPhysics = {
  "Which of the following is a unit for sound intensity level? W) Amplitude X) Watt Y) Decibel Z) Hertz": "Decibel",
  "In which of the following cases will the displacement of the object be the least? W) A 1.2-kilogram object moving 4 meters up an incline of 45 degrees X) A 3.1-kilogram object moving 3 meters on a flat surface Y) A 0.5-kilogram object moving 6 meters along a circle with circumference 6 meters Z) Cannot be determined from the information given": "A 0.5-kilogram object moving 6 meters along a circle with circumference 6 meters",
  "The length of a meter was re-defined in 1983 to be based on what physical quantity? W) A wavelength of krypton-86 radiation X) The distance light travels in a specific fraction of a second in a vacuum Y) The length of a one-kilogram bar of iridium Z) A specific fraction of the length of the meridian through Paris from the North Pole to the Equator": "The distance light travels in a specific fraction of a second in a vacuum",
  "In meters per second squared, what is the acceleration experienced by a 10-kilogram mass if it is being pushed by a 15-newton force?": "1.5",
  "Which of the following materials is the best thermal conductor? W) Glass X) A sheet of plastic Y) A block of aluminum Z) An air mattress": "A block of aluminum",
  "As a spring is compressed, which of the following best describes what happens to the amount of elastic potential energy stored in the spring? W) It increases X) It decreases Y) It is unchanged Z) It decreases, then increases": "It increases",
  "What is the SI derived unit for frequency?": "Hertz",
  "In kilogram-meters per second, what is the momentum of a 20-kilogram cart traveling at 3 meters per second?": "60",
  "Aside from momentum, what other general physical quantity can be expressed with the units of kilogram-meters per second?": "Impulse",
  "In millivolts, what voltage is needed to produce a current of 3 milliamperes over a piece of metal with a resistance of 2 ohms?": "6",
  "Suppose that a projectile was thrown vertically downwards from a height of 10 meters. If its speed at the ground was 20 meters per second, then to the nearest meter per second, what was its initial velocity?": "14",
  "Which of the following best explains why clouds appear white, but liquid water is transparent? W) Interference X) Radiation Y) Scattering Z) Diffraction": "Scattering",
  "Rank the following three objects in terms of increasing momentum: 1) A one-ton car traveling at 10 meters per second; 2) A one-and-a-half-ton car traveling at 10 meters per second; 3) A one-ton car traveling at 20 meters per second": "1, 2, 3"
};
MSChemistry = {
  "Which of the following has the highest pH? W) Sea water X) Lemon juice Y) Baking soda Z) Chlorine bleach": "Chlorine bleach",
  "What type of radioactive decay occurs when carbon-14 decays to nitrogen-14?": "Beta decay",
  "Argonne National Lab researchers are studying colloids using high-powered microscopes. Which of the following is an example of a colloid? W) Energy drink X) Salt water Y) Soda Z) Milk": "Milk",
  "Rutherford discovered that the nucleus contains what positively-charged particles?": "Protons",
  "What is the IUPAC name of AgNO3?": "Silver nitrate",
  "Dry ice is the solid form of what molecule?": "Carbon dioxide",
  "Scientists at Brookhaven National Lab are studying catalysts for the conversion of carbon dioxide to methanol. What general type of reaction is this? W) Synthesis X) Redox Y) Single replacement Z) Decomposition": "Redox",
  "Which of the following substances has a pH value that is less than 7? W) Vinegar X) Sodium bicarbonate Y) Soapy water Z) Ammonia": "Vinegar",
  "To one significant figure, what is the mass percent of hydrogen in water?": "10",
  "Researchers at Oak Ridge National Lab used chemical vapor deposition to grow large monolayer films of what form of carbon, touted for its unprecedented strength and high electrical conductivity?": "Graphene",
  "The atomic number of molybdenum is 42. What does this number indicate? W) Every atom has 42 total protons & neutrons in the nucleus X) Every atom has a mass of 42 a.m.u. Y) Every atom has 42 protons in the nucleus Z) Every atom will form bonds that measure 42 degrees": "Every atom has 42 protons in the nucleus",
  "In the balanced equation for the complete combustion of methane, what is the coefficient in front of methane?": "1",
  "Researchers at the National Energy Technology Lab have recovered pressurized ocean cores from the Gulf of Mexico that contain methane hydrates. When the methane that is extracted from these cores is fully combusted in oxygen to drive a heat engine, what are the two end products?": "Carbon dioxide and water"
};
MSEarthSpace = {
  "Which of the following is not considered a type of wetland? W) Fen X) Bog Y) Swamp Z) Bay": "Bay",
  "In our solar system, how many moons does the fourth planet from the Sun have? W) 0 X) 1 Y) 2 Z) 4": "2",
  "Which of the following is true about the water table?  W) It is deeper in summer than winter X) It does not vary under high pumping rates Y) It varies due to precipitation amounts Z) It is constant throughout the year": "It varies due to precipitation amounts",
  "Which of the following best approximates the ratio of the volume of Olympus Mons to that of Mauna Loa? W) 10 X) 50 Y) 100 Z) 1000": "100",
  "Calling a tsunami a tidal wave is misleading because of what characteristic of a tsunami? W) It is not a wave X) It is not caused by tides Y) It does not occur in the ocean Z) It only occurs during ebb tides": "It is not caused by tides",
  "Which of the following is an asterism as opposed to a constellation? W) Orion X) Big Dipper Y) Crux Z) Ursa Minor": "Big Dipper",
  "What is the name for the part of the Sun that, by definition, is completely hidden in a total eclipse?": "Photosphere",
  "What is the name for a strong ground-level wind system that emanates from a point source above and blows radially from the point of contact at ground level? W) Waterspout X) Downburst Y) Fire storm Z) Jet stream": "Downburst",
  "Which of the following best describes the pathway of aerobic respiration? W) Glucose is oxidized and oxygen is reduced X) Oxygen is oxidized and glucose is reduced Y) Both glucose and oxygen are oxidized Z) Both glucose and oxygen are reduced": "Glucose is oxidized and oxygen is reduced",
  "Which of the following occurs at an ocean-continent convergent boundary? W) Two tectonic plates move away from each other X) Oceanic crust will subduct under continental crust Y) Continental crust will subduct under oceanic crust Z) Two tectonic plates slide past each other": "Oceanic crust will subduct under continental crust",
  "Seismic waves propagate through Earth's interior following an earthquake. Identify all of the following three phases of matter through which P-waves can propagate: 1) Solid; 2) Liquid; 3) Gas": "All",
  "The solar system's asteroid belt is a group of asteroids orbiting together between the orbits of which two planets?": "Mars and Jupiter",
  "Crater counting is a method that can be used to estimate what feature of a moon or planet? W) Age X) Composition Y) Mass Z) Orbital velocity": "Age",
  "In our solar system, what planet has the fastest orbital velocity around the Sun?": "Mercury",
  "Identify all of the following three phases of the moon during which the tidal range is at a maximum: 1) New moon; 2) First quarter; 3) Full moon": "1 and 3",
  "Which of the following properties of water is most responsible for the tempering influence of the ocean on climate? W) Freezing point X) pH Y) Heat capacity Z) Density": "Heat capacity",
  "Which of the following is considered a mineral? W) Pearl X) Coal Y) Ice Z) Peat": "Ice",
  "Identify all of the following three glacial features that provide information about the direction a glacier flowed. 1) Striations; 2) Drumlins; 3) Basal slip": "1 and 2",
  "The Milky Way, Andromeda, and Maffei 1 are examples of what systems that can be found in space?": "Galaxy",
  "What planet was hypothesized to exist by mathematician Urbain Leverrier due to observed discrepancies in Uranus's orbit?": "Neptune",
  "Oceanographers use which of the following terms to describe global ocean circulation patterns? W) Density conveyor X) Isostatic conveyor Y) Thermohaline conveyor Z) Carbonate conveyor": "Thermohaline conveyor",
  "Barchan and transverse are types of what geologic feature?": "Dunes",
  "Earth’s magnetic field arises from movement in its outer core that is primarily composed of what two metals?": "Nickel and iron",
  "Rank the following three minerals in order of increasing Mohs hardness: 1) Fluorite; 2) Apatite; 3) Quartz": "1, 2, 3",
  "Seismic activity in the ocean may lead to what destructive phenomenon? W) Tsunamis X) Monsoons Y) Storm surge Z) Hurricanes": "Tsunamis",
  "Identify all of the following three stream features that result from deposition: 1) Cut bank; 2) Point bar; 3) Delta": "2, 3",
  "The cosmic background radiation originating from the big bang has been redshifted into what part of the electromagnetic spectrum?": "Microwave"
};
MSEnergy = {
  "Which of the following appliances typically uses the most electricity per unit time? W) Vacuum cleaner X) Hair dryer Y) 60-watt incandescent light bulb Z) Desktop computer in active mode": "Hair dryer",
  "Research at Lawrence Livermore National Laboratory is aimed at reducing methane emissions. According to the Energy Information Administration, which of the following fractions is closest to the estimate of the 100-year net global warming potential of methane? W) One-one-hundredth  X) One-fourth Y) Three-fourths Z) Nine-tenths": "One-fourth",
  "In the United States, which of the following renewable energy sources provides the smallest annual energy output? W) Solar X) Hydroelectric Y) Biomass Z) Wind": "Solar",
  "Which of the following is not a potential environmental concern related to concentrating solar plants? W) Generation of high temperatures X) Wildlife strikes with turbines Y) Use of large land areas Z) Use of water for cooling": "Wildlife strikes with turbines",
  "SunStop is a flexible film developed at the National Renewable Energy Lab that is capable of preventing what form of energy from entering a building through its windows? W) Acoustic waves X) Infrared light Y) Gamma radiation Z) Electricity": "Infrared light",
  "Which of the following energy transformations occurs in your muscles when you jump into the air? W) Thermal to kinetic X) Chemical to kinetic Y) Kinetic to chemical Z) Thermal to potential": "Chemical to kinetic",
  "What process occurs within the core of the Sun to produce heavy elements and energy from light elements?": "Fusion"
};
MSMath = {
  "Which of the following statements about a right triangle is NOT necessarily true? W) One angle measures 90 degrees X) The hypotenuse is the longest side Y) It has at least one obtuse angle Z) It has two acute angles": "It has at least one obtuse angle",
  "If p and q are consecutive integers, identify all of the following four numbers that are always odd: 1) p + q; 2) pq; 3) pq + 1; 4) (p + q)^2": "1, 3, 4",
  "What is 300 + 200 – 333?": "167",
  "What is the radius of the circle with equation x^2 + 4x + y^2 = 12?": "4",
  "If the discriminant of a quadratic equation is –9, which of the following best describes the roots of the equation? W) No roots X) 3 and -3 Y) Irrational Z) Complex": "Complex",
  "If Y is a point outside square ABCD, and triangle BYC is equilateral, what is the degree measure of angle BYA?": "15",
  "Identify all of the following 3 types of numbers that both π and √2 are: 1) Rational; 2) Irrational; 3) Real.": "2, 3",
  "If the length of each edge of a 3-centimeter cube is tripled, what is the volume, in cubic centimeters, of the resulting cube?": "729",
  "Calculate the mean of the following 4 numbers: 20, 10, 30, 40": "25",
  "Simplify the following expression: 3 times the square root of 8, minus the square root of 50, plus the square root of 32": "5√2",
  "Which of the following is not a possible type of triangle? W) Acute isoceles X) Acute scalene Y) Obtuse equilateral Z) Obtuse isosceles": "Obtuse equilateral",
  "In the alternating arithmetic sequence with first 3 terms –7, 9, –11, what is the sum of the first 11 terms in the sequence?": "–17",
  "If m is an integer and 20m is divisible by 6, which of the following could be m? W) 2 X) 3 Y) 4 Z) 5": "3",
  "What is the length of a space diagonal in a right rectangular prism with edges of lengths 5, 6, and 7?": "√110",
  "Sam completely fills a box with sand... How many feet tall is Max’s box?": "4",
  "Give one of the linear factors of 6x2 – 31x + 35": "3x – 5 or 2x – 7",
  "Identify all of the following three quantities... atomic nucleus...": "3",
  "If x and y are directly proportional, and x is 7 when y is 13, what is x when y is 39?": "21",
  "Fifty students at Maple Grove Academy take French or Spanish...": "25",
  "Two cross-country runners... head start?": "10",
  "What is the length of the hypotenuse of the right triangle with vertices at (4, 4), (10, 4), and (4, 8)?": "2√13",
  "Satellites that stay above the same spot on Earth while in orbit are in what type of orbit?": "Geostationary",
  "What is the discriminant of the quadratic polynomial 2x2 + 7x + 3?": "25",
  "Purity of gold is measured in karats...": "58",
  "Researchers at Brookhaven National Lab are constructing geometric figures...": "Octahedron",
  "What is the total surface area of a rectangular box having edge lengths of 4, 6, and 7?": "188",
  "If set A contains the four elements 1, 3, 5, and 7, and set B contains the four elements 1, 2, 3, and 4, then what elements are in the intersection of sets A and B?": "1 and 3",
  "What are the slope and y-intercept of the line containing the points (–12, –2) and (–8, 8)?": "Slope = 5/2 and y-intercept = 28",
  "What is the circumference of a circle of radius 7?": "14π",
  "Identify all of the following 4 terms that apply to the sequence with nth term given by 3n – 2: 1) geometric; 2) arithmetic; 3) increasing; 4) decreasing": "2 and 3",
  "Giving your answer as a fraction, what is the reciprocal of 4.5?": "2/9",
  "4 blue marbles, 3 green marbles, and 3 red marbles are in a jar...": "4/15"
};


HSQuestions = {
  "What is 125x27": "3375",
  "Find the mass of 1 mole of cuprous oxide, or Cu2O. Assume the atomic mass of copper is 64 and oxygen is 16.":
    "144",
};

